#!/bin/env python2.5
# Copyright (c) 2007 Tommy Yu
# This software is released under the GPLv3

# Interactive controller for mtmud

from mtmud.ctrl import mudctrl

if __name__ == '__main__':
    c = mudctrl()
    c.run()
