#!/bin/env python2.5
# Copyright (c) 2007 Tommy Yu
# This software is released under the GPLv3

# Interactive controller for mtmud

from mud import *
from server import *
from runner import *
try:
    import readline
except:
    pass

if __name__ == '__main__':
    def start():
        if not mudserv.isRunning():
            print 'Starting mudserv thread.'
            mudserv.start()
        else:
            print 'mudserv already started.'

    def stop():
        if mudserv.isRunning():
            print 'Stopping mudserv...',
            mudserv.stop()
            print 'done.'
        else:
            print 'mudserv not started.'

    def drive():
        if not driver.isRunning():
            print 'Starting driver thread.'
            driver.start()
        else:
            print 'driver already driving.'

    def brake():
        if driver.isRunning():
            print 'Stopping driver...',
            driver.stop()
            print 'done.'
        else:
            print 'driver not driving.'

    def debug():
        # lolhack
        global eval_mode
        if not eval_mode:
            print('Debug mode on.  Basic raw Python commands are now accepted.')
            print('To return to standard mudctrl mode, type "debug()" again.')
        eval_mode = not eval_mode
        if not eval_mode:
            return 'Debug mode off.'

    def quit():
        # lolhack
        raise EOFError

    driver = MudDriver()
    mudserv = MudServerController()
    mudserv.driver = driver
    active = True
    eval_mode = False
    prompts = {
        True: '>>> ',
        False: 'mudctrl> ',
    }
    root_server_cmd = {
         'start': start,
         'stop': stop,
         'quit': quit,
         'drive': drive,
         'brake': brake,
         'debug()': debug,
         '': str,  # lolhack
    }

    print 'Starting mtmud interactive shell.'
    while active:
        try:
            # XXX might want to use code.InteractiveConsole
            _s = raw_input(prompts[eval_mode])
            if eval_mode:
                try:
                    print eval(_s)
                except:
                    exec _s
            elif _s in root_server_cmd:
                root_server_cmd[_s]()
            else:
                print 'Invalid Command.'
        except EOFError:
            if eval_mode:
                eval_mode = False
            else:
                active = False
            print ''
        except KeyboardInterrupt:
            print('\nGot keyboard interrupt.'),
            if mudserv.isRunning():
                print('mudserv running, stopping...'),
                mudserv.stop()
                print 'done.'
            else:
                print('mudserv not running, terminating.')
                active = False
        except:
            print traceback.format_exc()
    # stop server if running
    if mudserv.isRunning():
        mudserv.stop()
    if driver.isRunning():
        driver.stop()

    # really quit.
    sys.exit()

