#!/usr/bin/env python
# Copyright (c) 2007 Tommy Yu
# This software is released under the GPLv3

# Interactive controller for mtj.mud

from mtj.mud.ctrl import mudctrl

if __name__ == '__main__':
    c = mudctrl()
    c.run()
